config/routes.rb
Rails.application.routes.draw do
  root 'contacts#index'

  resources :contacts do
    put 'share', on: :member
    post 'import', on: :collection
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  ARRAY_DELIMITER = ';'

  validates :first_name, :last_name, presence: true
  validates :emails, email: true
  validates :emails, presence: true, if: ->(contact) { contact.phones.blank? }
  validates :phones, presence: true, if: ->(contact) { contact.emails.blank? }
  validates :first_name, uniqueness: { scope: :last_name }

  scope :search, ->(str) {
    where("first_name ILIKE :str OR
           last_name ILIKE :str OR
           :str ILIKE ANY (emails) OR
           :str ILIKE ANY (phones)", str: str)
  }

  def name
    "#{first_name} #{last_name}"
  end

  %i(phones= emails=).each do |method|
    define_method(method) do |values|
      values = values.split(ARRAY_DELIMITER) if values.is_a?(String)
      values ||= []
      super(values.reject(&:blank?))
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy, :share]

  def index
    @contacts = params[:q].present? ? Contact.search(params[:q]) : Contact.all
    respond_to do |format|
      format.html
      format.csv { send_data ContactCsvService.export_to_csv }
    end
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to @contact, notice: t('.notice', resource: Contact.model_name.human)
    else
      render :new
    end
  end

  def update
    if @contact.update(contact_params)
      redirect_to @contact, notice: t('.notice', resource: Contact.model_name.human)
    else
      render :edit
    end
  end

  def destroy
    @contact.destroy
    redirect_to contacts_url, notice: t('.notice', resource: Contact.model_name.human)
  end

  def share
    ContactSharingMailer.share_contact(@contact.id, params.require(:email)).deliver_later
    redirect_to :back
  rescue ActionController::RedirectBackError
    redirect_to root_path
  end

  def import
    ContactCsvService.import_from_csv(params.require(:file).tempfile)
    redirect_to :back, notice: t('.notice', resource: Contact.model_name.human(count: 2))
  rescue ActionController::RedirectBackError
    redirect_to root_path, notice: t('.notice', resource: Contact.model_name.human(count: 2))
  end

  private

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, emails: [], phones: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.slim
= form_for @contact, data: { 'parsley-validate' => '' } do |f|
  - if @contact.errors.any?
    #error_explanation
    h2 = t('errors.messages.not_saved', count: @contact.errors.count, resource: Contact.model_name)
    ul
      - @contact.errors.full_messages.each do |msg|
        li =msg

  .field
    = f.label :first_name
    = f.text_field :first_name, required: true

  .field
    = f.label :last_name
    = f.text_field :last_name, required: true

  .field
    = f.label :emails
    - @contact.emails.each do |email|
      .field-with-btn
        = email_field_tag 'contact[emails][]', email, required: true
        = button_tag 'X', class: 'js-remove-field'
    = button_tag t('contacts.email.add'), class: 'js-add-field'
    .js-new-field.invisible
      .field-with-btn
        = email_field_tag 'contact[emails][]', nil
        = button_tag 'X', class: 'js-remove-field'

  .field
    = f.label :phones
    - @contact.phones.each do |phone|
      .field-with-btn
        = phone_field_tag 'contact[phones][]', phone, required: true
        = button_tag 'X', class: 'js-remove-field'
    = button_tag t('contacts.phone.add'), class: 'js-add-field'
    .js-new-field.invisible
      .field-with-btn
        = phone_field_tag 'contact[phones][]', nil
        = button_tag 'X', class: 'js-remove-field'

  hr
  .actions
    = f.submit

app/views/contacts/_share_form.html.slim
= form_tag share_contact_path, method: :put do
  .field
    = label_tag :email
    = email_field_tag :email

  .actions
    = submit_tag t('contacts.share')

app/views/contacts/edit.html.slim
h1 =t('contacts.edit')
== render 'form'

app/views/contacts/index.html.slim
.page-header
  = link_to t('contacts.new'), new_contact_path, class: 'btn'
  h1
    = t('contacts.index')

table.tables
  thead
    tr
      th= Contact.human_attribute_name(:name)
      th= Contact.human_attribute_name(:emails)
      th= Contact.human_attribute_name(:phones)
      th

  tbody
    - @contacts.each do |contact|
      tr
        td = link_to contact.name, contact
        td
          ul
            - contact.emails.each do |email|
              li = mail_to email
        td
          ul
            - contact.phones.each do |phone|
              li = phone
        td
          =< link_to t('contacts.edit'), edit_contact_path(contact), class: 'btn'
          =< link_to t('contacts.delete'), contact, data: {confirm: t('layouts.delete_confirm')}, method: :delete, class: 'btn btn-red'
hr

h2= t('contacts.import_contacts')
= form_tag import_contacts_path, multipart: true do
  .field
    = file_field_tag :file

  .actions
    = submit_tag t('contacts.import_contacts')

app/views/contacts/new.html.slim
h1 =t('contacts.new')
== render 'form'

app/views/contacts/show.html.slim
p
  strong First name:
  = @contact.first_name
p
  strong Last name:
  = @contact.last_name
p
  strong Emails:
  - @contact.emails.each do |email|
    p
      = email
p
  strong Phones:
  - @contact.phones.each do |phone|
    p
      = phone

= link_to t('contacts.edit'), edit_contact_path(@contact), class: 'btn'
hr
= render 'share_form'

app/views/layouts/application.html.slim
doctype html
html lang=I18n.locale
  head
    title
      = content_for(:title) || t('layouts.title')
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = content_for :head
  body
    header.navigation role='banner'
      .navigation-wrapper
        a#js-mobile-menu.navigation-menu-button =t('layouts.menu')
        nav role='navigation'
          ul#js-navigation-menu.navigation-menu.show
            li.nav-link.more
              = link_to Contact.model_name.human(count: 2)
              ul.submenu
                li
                  = link_to t('contacts.index'), contacts_path
                li
                  = link_to t('contacts.index_csv'), contacts_path(format: :csv)
                li
                  = link_to t('contacts.new'), new_contact_path
        .navigation-tools
          .search-bar
            = form_tag contacts_path, method: :get, role: 'search'
              = search_field_tag :q, params[:q]
              = button_tag :submit do
                = image_tag 'search-icon.png'
    section.container
      - if flash.any?
        .flashes
          - flash.each do |name, msg|
            div class=name
              = msg

      .wrapper
        = yield